### ISSUE TITLE
Does CipherShed verify the integrity of data?

### ISSUE THREAD

**Issue by netheril96** [CipherShed/CipherShed#42]
Like with authenticated encryption such as AES-GCM or with HMAC? 

Currently I am storing my sensitive info on Apple's encrypted dmg file, and they don't have integrity checking (I tried flipping some bits in the dmg file, and it mounts just fine). I wonder if it is the same for all encrypted containers.

**Comment by compul** [comment]
CipherShed, just as TrueCrypt, uses XTS-mode as encryption mode, which does not provide active integrity checks.(https://en.wikipedia.org/wiki/Disk_encryption_theory#XEX-based_tweaked-codebook_mode_with_ciphertext_stealing_.28XTS.29) However, with XTS, flipping a bit in the ciphertext results in a whole block being scrambled after decryption (in contrast to CBC-mode, where one can actually flip single bits, and attacks have already been demonstrated), which provides a certain extent of defense against ciphertext manipulation.

Block-by-block integrity checking using MACs is problematic in disk-encryption, since it would quite drastically reduce the volume size. Using MACs for single files within an encrypted volume would probably best fit your requirements. CipherShed itself does not do this. I presume there are tools out there that do this, though I do not know anything particular.

Also take a quick look at http://andryou.com/truecrypt/docs/authenticity-and-integrity.php.

**Comment by netheril96** [comment]
@compul 

CipherShed could also add a MAC in the header to verify against the whole ciphertext. It will be slow for large containers, but it could be optional, only for the most paranoid (like me).

**Comment by compul** [comment]
Indeed it would be very slow. Also, corruption in some place would trigger a warning, and you wouldn't know where it came from.

**Comment by netheril96** [comment]
OK, I guess I will write my own HMAC program to ensure integrity.
